"""Alert API routes."""
from flask import Blueprint, jsonify, request
from app.services.risk_engine import get_cached_alerts

alert_bp = Blueprint('alerts', __name__)

# In-memory historical alerts list (persisted across requests)
_alert_history = []


def _update_history(new_alerts):
    """Append new alerts to history (max 200)."""
    global _alert_history
    for alert in new_alerts:
        # Avoid duplicates based on timestamp + zone
        key = f"{alert['timestamp']}_{alert['zone_id']}"
        if not any(f"{a['timestamp']}_{a['zone_id']}" == key for a in _alert_history):
            _alert_history.insert(0, alert)
    _alert_history = _alert_history[:200]


@alert_bp.route('/api/alerts', methods=['GET'])
def get_alerts():
    """
    Get current active alerts.

    Returns alerts generated by the risk engine when zones are HIGH/MEDIUM risk.
    """
    alerts = get_cached_alerts()
    _update_history(alerts)

    return jsonify({
        'status': 'ok',
        'alerts': alerts,
        'count': len(alerts),
        'critical': sum(1 for a in alerts if a['risk_level'] == 'HIGH'),
    })


@alert_bp.route('/api/alerts/history', methods=['GET'])
def get_alerts_history():
    """
    Get historical alerts with optional filtering.

    Query params:
      - risk_level: HIGH, MEDIUM, LOW, or ALL (default: ALL)
      - hours: number of hours to look back (default: all)
    """
    risk_filter = request.args.get('risk_level', 'ALL')
    hours_filter = request.args.get('hours', None)

    alerts = list(_alert_history)

    # Filter by risk level
    if risk_filter and risk_filter != 'ALL':
        alerts = [a for a in alerts if a['risk_level'] == risk_filter]

    # Filter by time
    if hours_filter:
        try:
            from datetime import datetime, timedelta
            cutoff = (datetime.utcnow() - timedelta(hours=int(hours_filter))).isoformat()
            alerts = [a for a in alerts if a['timestamp'] >= cutoff]
        except (ValueError, KeyError):
            pass

    return jsonify({
        'status': 'ok',
        'alerts': alerts,
        'total': len(alerts),
        'filters': {
            'risk_level': risk_filter,
            'hours': hours_filter,
        },
    })
